export const itemshop = [
  {
    id: 1,
    name: 'ข้าวขาหมู',
    details: 'ขาหมูเน้นๆ ไข่ยางมะตูมเยิ้มๆ',
    price: 60,
    imageId: 'khamoo.jpg',
  },
  {
    id: 2,
    name: 'ข้าวมันไก่',
    details: 'ไก่เนื้อนุ่มพร้อมน้ำจิ้มสูตรพิเศษ',
    price: 50,
    imageId: "chickenRice.jpg",
  },
  {
    id: 3,
    name: 'ผัดไทยกุ้งสด',
    details: 'ผัดไทยเส้นนุ่ม กุ้งสดชิ้นโต',
    price: 70,
    imageId: 'pad-thai-shrimp.jpg',
  },
  {
    id: 4,
    name: 'ก๋วยเตี๋ยวเรือ',
    details: 'เส้นเหนียวนุ่ม ซุปเข้มข้น',
    price: 40,
    imageId: 'boat-noodles.jpg',
  },
  {
    id: 5,
    name: 'ส้มตำไทย',
    details: 'รสชาติจัดจ้าน ครบรส',
    price: 40,
    imageId: 'ppy-salad.jpg',
  },
  {
    id: 6,
    name: 'ข้าวผัดกุ้ง',
    details: 'ข้าวผัดหอมๆ พร้อมกุ้งสด',
    price: 55,
    imageId: 'fried-rice-shrimp.jpg',
  },
  {
    id: 7,
    name: 'ผัดกะเพราไก่',
    details: 'รสชาติจัดจ้าน เผ็ดกำลังดี',
    price: 50,
    imageId: 'kra-pao-chicken.jpg',
  },
  {
    id: 8,
    name: 'ข้าวหมูกรอบ',
    details: 'หมูกรอบ หนังกรอบ เนื้อนุ่ม',
    price: 60,
    imageId: 'pork-crisp.jpg',
  },
  {
    id: 9,
    name: 'ข้าวหน้าเป็ด',
    details: 'เนื้อเป็ดนุ่ม น้ำราดกลมกล่อม',
    price: 70,
    imageId: 'duck-rice.jpg',
  },
  {
    id: 10,
    name: 'ข้าวหมูแดง',
    details: 'หมูแดงเนื้อนุ่ม น้ำราดหอมหวาน',
    price: 55,
    imageId: 'sweet-pork-rice.jpg',
  },
  {
    id: 11,
    name: 'ยำวุ้นเส้น',
    details: 'วุ้นเส้นกรอบ รสชาติจัดจ้าน',
    price: 45,
    imageId: 'woonsen.jpg',
  },
  {
    id: 12,
    name: 'แกงเขียวหวาน',
    details: 'รสชาติเข้มข้น เผ็ดกำลังดี',
    price: 65,
    imageId: 'green-curry.jpg',
  },
];
